### ISSUE TITLE
move news articles from medium JSON to configurable links

### ISSUE THREAD

**Issue by acidjazz** [acidjazz/waa#160]
Articles will be stored in a `yaml` configuration similar to the following 

```yaml
articles:
    - url: https://medium.com/we-are-apartments/richmondmom-com-2823f4b78739
        feature: true
        front_page: true
  
    - url: https://medium.com/we-are-apartments/pennsylvania-company-establishes-fund-to-help-residents-8c7b1c376ac7
        featured: false
        front_page: false
```

* It will be suggested to start off with 9 articles, but the code will be fine with adding less or more.
* An article with `feature: true` will be featured at the top of the `/articles` page.
* The first three articles with `front_page: true` will show up on the home page.
* Upon deployment, the title and image will be pulled from the URL

- [x] remove the need to parse the medium JSON
- [x] make an easy to use config file easily editable with the 3 or more urls
- [x] update code based on urls upon compilation
